### PR TITLE
Gesture Record Script

### PR DESCRIPTION
**Pull request by vairasza**
Added a script that records following gestures: tilt left, tilt right, throw and neutral.

Besides tilt left and right, throw might have some interpretation space. Therefore i suggest - for now - to only record the throw gesture showcased in the paper [video at 02:23](https://youtu.be/KXO6Fr3sBIM?t=143).

Also, i propose to add a neutral gesture that is predicted when none of the desired gestures was performed. In this case, just standing with the recording device in neutral position, is sufficient - I guess?!

Maybe we can already add some data over the weekend (from different persons) so that first results can be discussed on monday. I suggest adding a **data** branch for this issue.

### CODE REVIEW

**Comment by tina-e** [comment]
> Besides tilt left and right, throw might have some interpretation space. Therefore i suggest - for now - to only record the throw gesture showcased in the paper [video at 02:23](https://youtu.be/KXO6Fr3sBIM?t=143).

👍🏼 

> Also, i propose to add a neutral gesture that is predicted when none of the desired gestures was performed. In this case, just standing with the recording device in neutral position, is sufficient - I guess?!

Maybe also add some data of device lying (e.g. on a table)

> Maybe we can already add some data over the weekend (from different persons) so that first results can be discussed on monday. I suggest adding a data branch for this issue.

👍🏼

**Comment by vairasza** [comment]
> > Also, i propose to add a neutral gesture that is predicted when none of the desired gestures was performed. In this case, just standing with the recording device in neutral position, is sufficient - I guess?!
> 
> Maybe also add some data of device lying (e.g. on a table)
> 

thats true. also to a certain degree, device should be tiltable in neutral position.

so neutral should contain:
- standing with device in neutral position
- device lying on table, or sth else
- tilting device a little bit
- moving with device

as gestures are only predicted while using a certain application, we can neglect mobile phone in pocket or similar; we can assume that person is standing straight in front of a screen?

**Comment by vairasza** [comment]
added default values for gather-data.py that fit our use case

**Comment by tina-e** [comment]
> > > Also, i propose to add a neutral gesture that is predicted when none of the desired gestures was performed. In this case, just standing with the recording device in neutral position, is sufficient - I guess?!
> > 
> > 
> > Maybe also add some data of device lying (e.g. on a table)
> 
> thats true. also to a certain degree, device should be tiltable in neutral position.
> 
> so neutral should contain:
> 
> * standing with device in neutral position
> * device lying on table, or sth else
> * tilting device a little bit
> * moving with device
> 
> as gestures are only predicted while using a certain application, we can neglect mobile phone in pocket or similar; we can assume that person is standing straight in front of a screen?

Establish connection between mobile device and PC as soon as mobile app is started/button clicked in mobile app... with this, we can check if there is an open connection and only handle recognized gestures if this connection exists? ... i guess we can discuss this on monday

**Pull request merged**
